spring.application.name=my-ai-agent
spring.ai.openai.chat.enabled=true
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0


spring.ai.ollama.chat.enabled=false

spring.ai.ollama.base-url=http://localhost:11434
logging.level.org.springframework.web.client=debug